### ISSUE TITLE
Why can't we recurse through the hierarchy?

### ISSUE THREAD

**Issue by waldoj** [openva/va-decoded#1]
[This](https://github.com/openva/va-decoded/blob/master/xslt/vacode.xslt#L29) isn't recursing through [this XML](https://github.com/openva/va-decoded/blob/master/xslt/sample_1.xml). Instead, it's getting the most deeply-nested element rather than just the first one. Here's the bit in question:

```
<structure>
    <xsl:for-each select="metadata/hierarchy">
        <xsl:apply-templates select="hierarchyLevel" />
    </xsl:for-each>
</structure>
```

[This is the template that's being applied](https://github.com/openva/va-decoded/blob/master/xslt/vacode.xslt#L83). What's the deal?

**Comment by thebestsophist** [comment]
I think it’s the difference between `apply-templates` and `call-template` that may be causing problems. I don’t have a standalone xslt parser set up at the moment, but I’m somewhat sure 5102efc194 should do what you need.

**Comment by waldoj** [comment]
This doesn't solve it...because I have this recursing infinitely. :) I just have to set a backstop on the recursion, and I think this'll do it! I'll get back on this tomorrow. Thanks so much!

**Comment by thebestsophist** [comment]
Is [this](https://gist.github.com/thebestsophist/1aebdee1db63fd994c84) what the transformed XML should look like?

**Comment by waldoj** [comment]
It is!

**Comment by thebestsophist** [comment]
Got it! 98c8255
The solution came to me when instead of using a counter to count the level, we should be counting the number of ancestors named `hierarchyLevel`.

(Also cleaned up my own `call-template` to use `apply-templates` again.)

**Comment by waldoj** [comment]
Woo! Not only does your PR fix it, but I basically understand _how_ it fixes it. :) Thanks for helping to create a universal LexisNexis XML parser for legal codes, and for teaching me something new!
