### ISSUE TITLE
Remove unit labels from structural identifiers

### ISSUE THREAD

**Issue by waldoj** [openva/va-decoded#5]
Right now we're generating this:

```
<unit label="title" identifier="TITLE 17.1." level="1">COURTS OF RECORD</unit>
```

It should be this:

```
<unit label="title" identifier="17.1." level="1">COURTS OF RECORD</unit>
```

That is, the `TITLE` is redundant, because we've already specified that it is a title within the `label` attribute.

**Comment by thebestsophist** [comment]
Does the identifier ever have characters? What if we remove every character that isn’t a number or “.”?

**Comment by waldoj** [comment]
Identifiers are, sadly, [a bag of pain](https://github.com/statedecoded/law-identifier). :) For example, the regex to identify Virginia identifiers is `([[0-9]{1,})([0-9A-Za-z\-\.]{0,3})-([0-9A-Za-z\-\.:]*)([0-9A-Za-z]{1,})`. If I properly understand what is possible within XSLT—and I may not!—then I think it's going to be easier to match the unit label (e.g., "title") than to try to match the section identifier (e.g., "§1-23A").

**Comment by waldoj** [comment]
I'm trying, fruitlessly, to get the core of this created, like such:

```
<xsl:attribute name="identifier">

    <xsl:variable name="unit_label" select="heading/desig" />
    <xsl:if test="contains($unit_label, 'TITLE ')">
        <xsl:variable name="unit_label" select="replace('$unit_label', 'TITLE ', '')" />
    </xsl:if>

    <xsl:value-of select="$unit_label"/>

</xsl:attribute>
```

It looks like, specifically, `<xsl:variable name="unit_label" select="replace('$unit_label', 'TITLE ', '')" />` is what's failing. I've tried replacing every changeable component of that (`name`, and the three `replace()` arguments), but I get an error (`Unable to perform XSL transformation on your XML file.`) every time.

**Comment by sdm7g** [comment]
Since you have switched to XSLT 2.0, you can just replace that whole block with this:

```
        <xsl:attribute name="identifier"><xsl:value-of select="replace(replace(normalize-space(heading/desig), '^(TITLE|SUBTITLE|ARTICLE|CHAPTER|PART) ', '' ), '.$', '')"/>
```

( Your current code is taking the string length, then doing a string replacement, which may yield a shorter length result, then using the original string length in you substring function. That's why it's not cutting off the final character. ) 

(Edit: inserted a normalize-space(), to make it whitespace tolerant, just in case. )

**Comment by waldoj** [comment]
It's amazing what foolish things one can do when using an unfamiliar programming language. :) Thank you!
